//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetFNCv18._1.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Intranet_FNCEntities : DbContext
    {
        public Intranet_FNCEntities()
            : base("name=Intranet_FNCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Modulo> Modulo { get; set; }
        public virtual DbSet<TipoRol> TipoRol { get; set; }
        public virtual DbSet<TipoRol_Modulo> TipoRol_Modulo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioRol> UsuarioRol { get; set; }
        public virtual DbSet<Acceso> Acceso { get; set; }
        public virtual DbSet<GestionDocumental> GestionDocumental { get; set; }
        public virtual DbSet<Log_Acceso_Usuario> Log_Acceso_Usuario { get; set; }
    }
}
