//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntranetFNCv18._1.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoRol_Modulo
    {
        public int IdTipoRol_Modulo { get; set; }
        public int IdTipoRol { get; set; }
        public int IdModulo { get; set; }
    
        public virtual Modulo Modulo { get; set; }
    }
}
